### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by alonalibarmn** [guttir14/SoT-Hook#8] opened 2020-11-01 13:39 UTC
![image](https://user-images.githubusercontent.com/71559074/97804405-614bf600-1c58-11eb-9702-f7705a2251a6.png)

**Comment by guttir14** [comment] 2020-11-01 18:43
Duplicate of #2

**Closed by guttir14** 2020-11-01 18:43 UTC

**Comment by cheeriosbaby** [comment] 2022-04-29 23:17
> Duplicate of #2

can you ever post a fully updated sot hook?
